# app:
#    name: My Application 2

test: Just testing something here real quickly

my.list.values: One, Two, Three

dbvalues: "{connectionString: 'http://__', userName: 'foo', password: '123'}"

db:
  connection: "{connectionString: 'http://__', userName: 'foo', password: '123'}"
  host: 127.0.0.1
  port: 1200